"""create channel table

Revision ID: 89054a5d60a1
Revises: 521ad963c061
Create Date: 2022-08-20 16:45:55.526431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89054a5d60a1'
down_revision = '521ad963c061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('channel_pic', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    # ### end Alembic commands ###
